# Generated by Django 2.2.7 on 2022-08-09 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stat_micro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securitystats',
            name='id',
        ),
        migrations.AlterField(
            model_name='securitystats',
            name='ticker',
            field=models.CharField(max_length=12, primary_key=True, serialize=False, unique=True),
        ),
    ]
