# Generated by Django 2.2.7 on 2022-08-09 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stat_micro', '0003_auto_20220809_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='securitystats',
            name='cur_price',
            field=models.FloatField(null=True),
        ),
    ]
