# Generated by Django 2.2.7 on 2022-08-25 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stat_micro', '0004_securitystats_cur_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='securitystats',
            name='down_sd',
            field=models.FloatField(null=True),
        ),
    ]
