# Generated by Django 2.2.7 on 2022-08-04 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_name', models.CharField(max_length=120)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sharpe_analysis.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('security_type', models.CharField(choices=[('Equity', 'Equity'), ('Bond', 'Bond'), ('Crypto', 'Crypto')], max_length=120)),
                ('ticker', models.CharField(max_length=12)),
                ('amount', models.FloatField()),
                ('portfolio_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sharpe_analysis.Portfolio')),
            ],
        ),
    ]
