# Generated by Django 2.2.7 on 2022-08-04 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharpe_analysis', '0002_client_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='client_name',
        ),
        migrations.AddField(
            model_name='client',
            name='first_name',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='last_name',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
