# Generated by Django 2.2.7 on 2022-08-06 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sharpe_analysis', '0004_auto_20220806_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='security',
            name='portfolio_parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sharpe_analysis.Portfolio'),
        ),
    ]
