# Generated by Django 2.2.7 on 2022-08-09 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharpe_analysis', '0005_auto_20220806_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='sharpe',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='valatrisk',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='ytd',
            field=models.FloatField(default=0),
        ),
    ]
