# Generated by Django 2.2.7 on 2022-08-09 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharpe_analysis', '0006_auto_20220809_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='sharpe',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='valatrisk',
            field=models.FloatField(default=0),
        ),
    ]
