# Generated by Django 2.2.7 on 2022-08-25 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharpe_analysis', '0007_auto_20220809_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='sortino',
            field=models.FloatField(default=0),
        ),
    ]
