# Generated by Django 2.2.7 on 2022-08-26 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharpe_analysis', '0008_portfolio_sortino'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='top3',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='total_val',
            field=models.FloatField(default=0),
        ),
    ]
